### ISSUE TITLE
`echo_service` test is failing CI

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/qp2p#108]
See https://github.com/maidsafe/quic-p2p/pull/107/checks?check_run_id=677634467#step:8:533

Extract from logs
```
  18: std::panic::catch_unwind
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  19: test::run_test_in_process
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libtest\lib.rs:542
  20: test::run_test::run_test_inner::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libtest\lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    tests::echo_service

test result: FAILED. 21 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p quic-p2p --lib'
##[error]The process 'C:\Rust\.cargo\bin\cargo.exe' failed with exit code 101
```

**Comment by S-Coyle** [comment]
Re-running CI seems to pass now - https://github.com/maidsafe/quic-p2p/actions/runs/104663034
Closing this issue and if this fails again we can re-open for investigation

**Comment by S-Coyle** [comment]
Re-opening as another 2 instances of this have appeared recently:
* https://github.com/maidsafe/quic-p2p/runs/790312120?check_suite_focus=true#step:8:575
* https://github.com/maidsafe/quic-p2p/pull/124/checks?check_run_id=835181068#step:6:586

**Comment by connec** [comment]
Gonna close this because CI has been stable for some time.
