### ISSUE TITLE
Release a 0.7.1 on crates.io with an updated readme which links to the new crates.io package

### ISSUE THREAD

**Issue by caemor** [maidsafe/qp2p#156]
For users of an older version it's difficult to see that the package is continued under a different name. Therefore I would propose to release a 0.7.1 on crates.io with a readme which links to the new package.

**Comment by S-Coyle** [comment]
Thanks for the nudge here @caemor , completely slipped my mind - I'll get that done

**Comment by S-Coyle** [comment]
Done - https://crates.io/crates/quic-p2p

**Comment by caemor** [comment]
Thanks :+1:
