### ISSUE TITLE
re-export tokio

### ISSUE THREAD

**Issue by GilRtr** [maidsafe/qp2p#170]
**Describe the bug**
Currently, someone using this crate has to depend on it as well as on the tokio crate, this is bad because
- A user should not have to depend on two crates in order to use one.
- If a user depends on a different version than this crate tokio is duplicated,
  also if the version the user depends on is a breaking change of the one qp2p does, that could create problems since tokio is a runtime.

**To Reproduce**
1. depend on this crate (`cargo add qp2p`)
2. run some code
3. realize you can't use `.await` syntax
4. depend on tokio (annoying)
5. If versions are incompatible: code `panic`s in a really weird way

**Expected behavior**
This crate re-exports tokio and that is the runtime you use

**Screenshots**
```toml
[dependencies]
qp2p = "0.8.8"
tokio = { version = "~0.2", features = ["rt-threaded", "macros"] }
```

**Desktop (please complete the following information where applicable):**
 - quic-p2p: 0.8.8

**Additional context**
I'd be happy to create the pull request for this fix and all the documentation corrections. I'll also add the relevant tokio features to this crate and give them a `tokio-` prefix.
In the end you should be able to use the crate like this:
```toml
qp2p = { version = "0.9.0", features = ["tokio-rt-threaded"] }
```
and use tokio like this:
```rust
use qp2p::rt;

#[rt::main]
async fn main() {}
```
or like this: (IMO less elegant but easier to adopt)
```rust
use qp2p::tokio;

#[tokio::main]
async fn main() {}
```

**Comment by nashley** [comment]
We may want `quinn` to re-export `tokio` to us.

**Comment by nashley** [comment]
Relates to https://github.com/quinn-rs/quinn/issues/1016

**Comment by nashley** [comment]
@GilRtr upstream (`quinn`) doesn't want to export tokio's feature flags, which would prevent us from doing so as well: https://github.com/quinn-rs/quinn/pull/1043#issuecomment-788885788
Personally I think their position makes sense, since consumers could always use their own `tokio` instance if they want to customize it.
Do you feel strongly about allowing users to enable tokio's feature flags?

**Comment by nashley** [comment]
I closed the upstream PR since I'm no longer sure that this is a good idea.

**Comment by connec** [comment]
I'm going to close this as well, on the same basis. Now that tokio has a stable release, compatibility should be less of an issue as well.
