### ISSUE TITLE
How qp2p do peer discovery?

### ISSUE THREAD

**Issue by so-schen** [maidsafe/qp2p#459]
I am searching guideline about peer discovery support in qp2p, is it supported by this crate?

**Comment by dirvine** [comment]
This is an unmaintained crate, but peer discovery was done via kademlia and not in this crate IIRC.

**Comment by gftea** [comment]
If this is unmaintained, any suggestion of replacement?
Any example that integrate kademila with this crate also? 
Thanks @dirvine

**Comment by dirvine** [comment]
We switched to use rust-libp2p it's very good and includes kademlia

**Comment by so-schen** [comment]
Thank you!
