### ISSUE TITLE
Implement bootstrap blacklist

### ISSUE THREAD

**Issue by madadam** [maidsafe/qp2p#52]
Might be needed to handle malicious / malfunctioning proxies to avoid attempts to connect to them again and again.

**Comment by connec** [comment]
With the removal of `BootstrapCache` and `Config::bootstrap_peers`, this is now a decision the caller can make whenever they call `Endpoint::new` or `Endpoint::connect_to_any`. There seems to be quite some to-and-fro in how responsibilities are divided between `safe_network` and `qp2p`, so perhaps we will want something like this in future, but for now `qp2p` is on a diet, so I'm going to close this.
